import { Category, Course, FeaturedCourse, User } from "../types/courses";

export const mockUser: User = {
  name: "Alex",
  avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCv67l6Cl8RJDczacAAglmg65vGqXngLByQPFnqsFoB1y_NoQDF1HvJJ8dlEwnBcBP0DajD7BtyJjiUowMF79xhwCh07edg8jyT7-Itl4rqv47LA4WIP7FBRxgDZWFa9PTZuagmPt1COiUec_UNOHUioMmfAAViLGe-UnBNy6rSe15oAEE4eb4CinkIWpZaMdDMiOISr1S5gT7kzle3eA9nF8y3pIdVZzKISPaqT7BqdX6-TfaeznKCFrRJdkm7QIRZs_54RhgkmNSw",
  streak: 12,
  isOnline: true,
  email: "alex.chen@example.com",
  subscription: {
    type: "Pro Member",
    status: "active",
  },
};

export const mockFeaturedCourse: FeaturedCourse = {
  id: "1",
  title: "The Psychology of Money",
  description: "Timeless lessons on wealth, greed, and happiness doing well with money.",
  category: "Economics",
  imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCOY7WUPoYPR2giHfrtpS0SjcJYJC1eL3oOw5psDJFS123S_egD3tPZLlWNS9M8aKyjEs4QhRKGB1o8Mk7kUykMZK32AyXm114rWJyrPPRHa8pFb4XoJZqbM9v4dZ-yZmCYyTC3c_ZKjlgcgeArjGni0vjw11xgxOhKT1uOktu5DnbMg2CCi-abNtJvSNnWfoALDsRdaL-hu6WilSZzE4Q6hy1yswNwpRAyY8-r4T_3uy_dRr0VwjoT1cd1IXsSs_NVr5jrYd7HjyiU",
  duration: 0,
  lessons: 5,
  progress: 100,
  timeRemaining: 5,
  totalChapters: 5,
  chapters: [
    { id: "1-1", title: "The Renaissance Boom", duration: 5 },
    { id: "1-2", title: "The Modern Auction House", duration: 7 },
    { id: "1-3", title: "NFTs and the Future", duration: 6 },
    { id: "1-4", title: "Wealth and Happiness", duration: 8 },
    { id: "1-5", title: "Building Long-term Wealth", duration: 9 },
  ],
};

export const mockTrendingCourses: Course[] = [
  {
    id: "2",
    title: "Modern Art Movements, this is a really long title that should be truncated",
    description: "",
    category: "Art",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCWDW5nCrCmmujKugk70eawdAt0y_8VcSPpvEMjsT9oo_EgkmIm2dHvFae58t365G0jBv8_Zn-HhYXxWOX1cHGPHPrZmv4UFF2AD6O2S-R3AVF8RW179bRThrHAX3zhxduFZFI9fRqXHbDQzO9kFzzkD4p8LzZvt6k3HgIF6UrC7wgsFhdPv3kuWkbR3d9Hhb6nHblfw8-xHlbR9NIO-S704_NGEFyX1XEuzvn1hwUYxxdYjzp2gTzBz_rLLBAVsVB8kghSycDv7d5E",
    duration: 0,
    lessons: 8,
    totalChapters: 8,
    progress: 100,
    chapters: [
      { id: "2-1", title: "Introduction to Modern Art", duration: 6 },
      { id: "2-2", title: "Impressionism and Post-Impressionism", duration: 7 },
      { id: "2-3", title: "Cubism and Abstraction", duration: 8 },
      { id: "2-4", title: "Surrealism and Dada", duration: 6 },
      { id: "2-5", title: "Abstract Expressionism", duration: 7 },
      { id: "2-6", title: "Pop Art Movement", duration: 5 },
      { id: "2-7", title: "Minimalism and Conceptual Art", duration: 6 },
      { id: "2-8", title: "Contemporary Art Today", duration: 7 },
    ],
  },
  {
    id: "3",
    title: "Cold War Geopolitics",
    description: "",
    category: "History",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPMFHpQQ93RNsLXJo8ZWjqovXj29idGeOok4fLC4Ma-rMFA2BrDqDE4HDMdcCyu189rtus9hQ6TIKfLFFk8v7k3rL6TAaNzVjZEcXnlGP1kvmwbJ0BKTv1v4ZKgfkoFzEogHK2xqP0KznNuPCkzOTVTyEVKODApG1E5ujM74485EyTWTBlJP9gLFqa9TVLOzPOiWdwRbQja3UAPdRAjaCxtm6t4GBGlEjfRhl2R4sE7vOU1L7aII5bTP9AO3jQ7pks1ApmAn8plpv9",
    duration: 0,
    lessons: 12,
    progress: 0,
    totalChapters: 12,
    chapters: [
      { id: "3-1", title: "Origins of the Cold War", duration: 8 },
      { id: "3-2", title: "The Iron Curtain", duration: 6 },
      { id: "3-3", title: "The Berlin Blockade", duration: 7 },
      { id: "3-4", title: "Korean War", duration: 8 },
      { id: "3-5", title: "The Space Race", duration: 7 },
      { id: "3-6", title: "Cuban Missile Crisis", duration: 9 },
      { id: "3-7", title: "Vietnam War", duration: 10 },
      { id: "3-8", title: "Détente and Arms Control", duration: 7 },
      { id: "3-9", title: "Soviet Invasion of Afghanistan", duration: 6 },
      { id: "3-10", title: "Reagan and the Second Cold War", duration: 8 },
      { id: "3-11", title: "Fall of the Berlin Wall", duration: 7 },
      { id: "3-12", title: "Collapse of the Soviet Union", duration: 9 },
    ],
  },
  {
    id: "4",
    title: "Supply & Demand",
    description: "",
    category: "Economics",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAJwpEhNwM3-Jd0v-rVvTyRGrmCaSBIQMuWv926Bxlynio57bB_MzdUr50iFz4XeNoA3eL01ryAcylUxfVIarxCZYr2oUicaFy_VBU0QDiqGM4Z5oXrK6Z_O7zrE3D9h8f8MJ4_OL53BG4Z1HYwTmLjgXTvG398a_tExUCXRtSGJyG1nDbp12HeJ6Wcj40mEfB8yvYjcyFhc422PrQ_cqZkQUY6vjVy8Wl8oZrM6GtTKD22QEk1l8ny8cbc12v7MmB-lJjBsZCdu8nf",
    duration: 0,
    lessons: 6,
    totalChapters: 6,
    progress: 100,
    chapters: [
      { id: "4-1", title: "Understanding Supply", duration: 5 },
      { id: "4-2", title: "Understanding Demand", duration: 5 },
      { id: "4-3", title: "Market Equilibrium", duration: 6 },
      { id: "4-4", title: "Price Elasticity", duration: 7 },
      { id: "4-5", title: "Shifts in Supply and Demand", duration: 6 },
      { id: "4-6", title: "Real-World Applications", duration: 7 },
    ],
  },
];

export const mockRecommendedCourses: Course[] = [
  {
    id: "5",
    title: "Stoicism in Modern Life",
    description: "How ancient wisdom can help you navigate modern stress.",
    category: "Philosophy",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDSJl-qLvznExOX21MrEsIkM6uZ19Q1J8-nBbxbtP36M5Unbo2MrtYx2gEA2n1MU9WebfwWHphpmuYaG3knKlXJZEybV55wha4Ngu78_EpMvgYGi04Z6YRsSazwx9CGEhi8ua5HctpsScER2UXzRWI0d_ZlgHvpqCc4HmDyGvlWfOvGYMTNe5818HUFAaisE6H3WLqffPsnFKLpIYsBfLaZQJ9gXSx0-H8gZZeJ8YFssRtPHpBYnoLlcdwOocqkw4tHFu-sEdFdB4eY",
    duration: 15,
    lessons: 5,
    progress: 100,
    totalChapters: 5,
    chapters: [
      { id: "5-1", title: "Introduction to Stoicism", duration: 3 },
      { id: "5-2", title: "The Dichotomy of Control", duration: 3 },
      { id: "5-3", title: "Managing Negative Emotions", duration: 3 },
      { id: "5-4", title: "Virtue and Character", duration: 3 },
      { id: "5-5", title: "Applying Stoicism Today", duration: 3 },
    ],
  },
  {
    id: "6",
    title: "CRISPR & Gene Editing",
    description: "Understanding the future of human biology and ethics.",
    category: "Science",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDl9AkFDrPkVu9kE_S5sqhtazV1tqSZqKcHJTnvyf0FCpHEwvKB_RbGqkMK7ZD5NPTitC-FeYpPD1QxFTv5nqLy8cXMAAN1hKnlehklelrEF49TQNM3sfQ_vy8BgN34x-_8Dmbk6_uHPD5QViL_pv7qlAuxC4CC7P4SjppnOp9OxXi-s75-QUpEuHMapfH_aoKChKlSqQtomm6VlHGTtQ_z9GgmJkWsqvUV5yLfjYVXQaqO1PeSlGtpTYYwO-u8n39vxYo9IIfZ4ndK",
    duration: 8,
    lessons: 4,
    progress: 0,
    totalChapters: 4,
    chapters: [
      { id: "6-1", title: "What is CRISPR?", duration: 2 },
      { id: "6-2", title: "How Gene Editing Works", duration: 2 },
      { id: "6-3", title: "Medical Applications", duration: 2 },
      { id: "6-4", title: "Ethical Considerations", duration: 2 },
    ],
  },
];

export const mockCategories: Category[] = ["For You", "Culture", "Art", "Economics", "Politics", "History"];

export interface Subtopic {
  id: string;
  title: string;
  description: string;
  courses: Course[];
}

export interface TopicCourses {
  topicId: string;
  subtopics: Subtopic[];
}

const imageUrls = [
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCOY7WUPoYPR2giHfrtpS0SjcJYJC1eL3oOw5psDJFS123S_egD3tPZLlWNS9M8aKyjEs4QhRKGB1o8Mk7kUykMZK32AyXm114rWJyrPPRHa8pFb4XoJZqbM9v4dZ-yZmCYyTC3c_ZKjlgcgeArjGni0vjw11xgxOhKT1uOktu5DnbMg2CCi-abNtJvSNnWfoALDsRdaL-hu6WilSZzE4Q6hy1yswNwpRAyY8-r4T_3uy_dRr0VwjoT1cd1IXsSs_NVr5jrYd7HjyiU",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuBPMFHpQQ93RNsLXJo8ZWjqovXj29idGeOok4fLC4Ma-rMFA2BrDqDE4HDMdcCyu189rtus9hQ6TIKfLFFk8v7k3rL6TAaNzVjZEcXnlGP1kvmwbJ0BKTv1v4ZKgfkoFzEogHK2xqP0KznNuPCkzOTVTyEVKODApG1E5ujM74485EyTWTBlJP9gLFqa9TVLOzPOiWdwRbQja3UAPdRAjaCxtm6t4GBGlEjfRhl2R4sE7vOU1L7aII5bTP9AO3jQ7pks1ApmAn8plpv9",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuAJwpEhNwM3-Jd0v-rVvTyRGrmCaSBIQMuWv926Bxlynio57bB_MzdUr50iFz4XeNoA3eL01ryAcylUxfVIarxCZYr2oUicaFy_VBU0QDiqGM4Z5oXrK6Z_O7zrE3D9h8f8MJ4_OL53BG4Z1HYwTmLjgXTvG398a_tExUCXRtSGJyG1nDbp12HeJ6Wcj40mEfB8yvYjcyFhc422PrQ_cqZkQUY6vjVy8Wl8oZrM6GtTKD22QEk1l8ny8cbc12v7MmB-lJjBsZCdu8nf",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuDSJl-qLvznExOX21MrEsIkM6uZ19Q1J8-nBbxbtP36M5Unbo2MrtYx2gEA2n1MU9WebfwWHphpmuYaG3knKlXJZEybV55wha4Ngu78_EpMvgYGi04Z6YRsSazwx9CGEhi8ua5HctpsScER2UXzRWI0d_ZlgHvpqCc4HmDyGvlWfOvGYMTNe5818HUFAaisE6H3WLqffPsnFKLpIYsBfLaZQJ9gXSx0-H8gZZeJ8YFssRtPHpBYnoLlcdwOocqkw4tHFu-sEdFdB4eY",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuDl9AkFDrPkVu9kE_S5sqhtazV1tqSZqKcHJTnvyf0FCpHEwvKB_RbGqkMK7ZD5NPTitC-FeYpPD1QxFTv5nqLy8cXMAAN1hKnlehklelrEF49TQNM3sfQ_vy8BgN34x-_8Dmbk6_uHPD5QViL_pv7qlAuxC4CC7P4SjppnOp9OxXi-s75-QUpEuHMapfH_aoKChKlSqQtomm6VlHGTtQ_z9GgmJkWsqvUV5yLfjYVXQaqO1PeSlGtpTYYwO-u8n39vxYo9IIfZ4ndK",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuCWDW5nCrCmmujKugk70eawdAt0y_8VcSPpvEMjsT9oo_EgkmIm2dHvFae58t365G0jBv8_Zn-HhYXxWOX1cHGPHPrZmv4UFF2AD6O2S-R3AVF8RW179bRThrHAX3zhxduFZFI9fRqXHbDQzO9kFzzkD4p8LzZvt6k3HgIF6UrC7wgsFhdPv3kuWkbR3d9Hhb6nHblfw8-xHlbR9NIO-S704_NGEFyX1XEuzvn1hwUYxxdYjzp2gTzBz_rLLBAVsVB8kghSycDv7d5E",
];

const getRandomImage = () => imageUrls[Math.floor(Math.random() * imageUrls.length)];

export const mockCoursesByTopic: TopicCourses[] = [
  {
    topicId: "history",
    subtopics: [
      {
        id: "european-history",
        title: "European History",
        description: "From the Renaissance to modern Europe",
        courses: [
          {
            id: "eh-1",
            title: "The Renaissance Era",
            description: "Exploring the cultural and artistic revolution of the Renaissance",
            category: "History",
            imageUrl: imageUrls[0],
            duration: 45,
            lessons: 8,
            progress: 100,
            chapters: [],
          },
          {
            id: "eh-2",
            title: "Medieval Europe",
            description: "Understanding the Middle Ages and feudal society",
            category: "History",
            imageUrl: imageUrls[0],
            duration: 50,
            lessons: 10,
            progress: 0,
            chapters: [],
          },
          {
            id: "eh-3",
            title: "The Age of Enlightenment",
            description: "Intellectual movements that shaped modern Western thought",
            category: "History",
            imageUrl: imageUrls[1],
            duration: 42,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "eh-4",
            title: "The Industrial Revolution",
            description: "How technological innovation transformed European society",
            category: "History",
            imageUrl: imageUrls[2],
            duration: 55,
            lessons: 11,
            progress: 0,
            chapters: [],
          },
          {
            id: "eh-5",
            title: "Modern European Union",
            description: "The formation and evolution of European integration",
            category: "History",
            imageUrl: imageUrls[3],
            duration: 38,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "eh-6",
            title: "The French Revolution",
            description: "The social and political upheaval that reshaped France",
            category: "History",
            imageUrl: imageUrls[4],
            duration: 48,
            lessons: 10,
            progress: 0,
            chapters: [],
          },
          {
            id: "eh-7",
            title: "World War I Origins",
            description: "Understanding the complex causes of the Great War",
            category: "History",
            imageUrl: imageUrls[5],
            duration: 52,
            lessons: 12,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "world-wars",
        title: "World Wars",
        description: "Understanding the conflicts that shaped the modern world",
        courses: [
          {
            id: "ww-1",
            title: "World War II: A Comprehensive Study",
            description: "The global conflict that changed the course of history",
            category: "History",
            imageUrl: imageUrls[1],
            duration: 60,
            lessons: 12,
            progress: 0,
            chapters: [],
          },
          {
            id: "ww-2",
            title: "Cold War History",
            description: "The ideological struggle between superpowers",
            category: "History",
            imageUrl: imageUrls[1],
            duration: 55,
            lessons: 11,
            progress: 0,
            chapters: [],
          },
          {
            id: "ww-3",
            title: "The Pacific Theater",
            description: "Naval battles and island campaigns in World War II",
            category: "History",
            imageUrl: imageUrls[2],
            duration: 47,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "ww-4",
            title: "The Holocaust",
            description: "Understanding one of history's darkest chapters",
            category: "History",
            imageUrl: imageUrls[3],
            duration: 58,
            lessons: 13,
            progress: 0,
            chapters: [],
          },
          {
            id: "ww-5",
            title: "Post-War Reconstruction",
            description: "How Europe rebuilt after World War II",
            category: "History",
            imageUrl: imageUrls[4],
            duration: 44,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "ancient-civilizations",
        title: "Ancient Civilizations",
        description: "Exploring the foundations of human civilization",
        courses: [
          {
            id: "ac-1",
            title: "Ancient Rome: Rise and Fall",
            description: "The empire that dominated the Mediterranean world",
            category: "History",
            imageUrl: imageUrls[0],
            duration: 56,
            lessons: 14,
            progress: 100,
            chapters: [],
          },
          {
            id: "ac-2",
            title: "Ancient Greece: Democracy and Philosophy",
            description: "The birthplace of Western civilization",
            category: "History",
            imageUrl: imageUrls[1],
            duration: 49,
            lessons: 10,
            progress: 0,
            chapters: [],
          },
          {
            id: "ac-3",
            title: "Ancient Egypt: Pharaohs and Pyramids",
            description: "The civilization along the Nile River",
            category: "History",
            imageUrl: imageUrls[2],
            duration: 43,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "ac-4",
            title: "Mesopotamia: Cradle of Civilization",
            description: "The first cities and writing systems",
            category: "History",
            imageUrl: imageUrls[3],
            duration: 41,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "american-history",
        title: "American History",
        description: "The story of the United States from colonization to today",
        courses: [
          {
            id: "ah-1",
            title: "The American Revolution",
            description: "The birth of a new nation",
            category: "History",
            imageUrl: imageUrls[4],
            duration: 46,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "ah-2",
            title: "The Civil War",
            description: "The conflict that defined America",
            category: "History",
            imageUrl: imageUrls[5],
            duration: 54,
            lessons: 11,
            progress: 0,
            chapters: [],
          },
          {
            id: "ah-3",
            title: "The Great Depression",
            description: "Economic crisis and recovery in the 1930s",
            category: "History",
            imageUrl: imageUrls[0],
            duration: 39,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
        ],
      },
    ],
  },
  {
    topicId: "economics",
    subtopics: [
      {
        id: "macroeconomics",
        title: "Macroeconomics",
        description: "Understanding the economy at a national and global level",
        courses: [
          {
            id: "macro-1",
            title: "Supply & Demand",
            description: "Fundamental principles of market economics",
            category: "Economics",
            imageUrl: imageUrls[2],
            duration: 30,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
          {
            id: "macro-2",
            title: "Economic Growth",
            description: "How economies expand and develop over time",
            category: "Economics",
            imageUrl: imageUrls[2],
            duration: 40,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
          {
            id: "macro-3",
            title: "Inflation and Monetary Policy",
            description: "Understanding price levels and central banking",
            category: "Economics",
            imageUrl: imageUrls[3],
            duration: 35,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "macro-4",
            title: "Unemployment and Labor Markets",
            description: "The dynamics of job markets and employment",
            category: "Economics",
            imageUrl: imageUrls[4],
            duration: 33,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
          {
            id: "macro-5",
            title: "International Trade",
            description: "Global commerce and trade agreements",
            category: "Economics",
            imageUrl: imageUrls[5],
            duration: 37,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
          {
            id: "macro-6",
            title: "Fiscal Policy and Government Spending",
            description: "How governments influence economic activity",
            category: "Economics",
            imageUrl: imageUrls[0],
            duration: 32,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "microeconomics",
        title: "Microeconomics",
        description: "Individual markets and consumer behavior",
        courses: [
          {
            id: "micro-1",
            title: "Consumer Choice Theory",
            description: "How individuals make economic decisions",
            category: "Economics",
            imageUrl: imageUrls[1],
            duration: 28,
            lessons: 5,
            progress: 0,
            chapters: [],
          },
          {
            id: "micro-2",
            title: "Market Structures",
            description: "Competition, monopolies, and market power",
            category: "Economics",
            imageUrl: imageUrls[2],
            duration: 36,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "micro-3",
            title: "Production and Costs",
            description: "How firms produce goods and services",
            category: "Economics",
            imageUrl: imageUrls[3],
            duration: 31,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
          {
            id: "micro-4",
            title: "Game Theory",
            description: "Strategic decision making in economics",
            category: "Economics",
            imageUrl: imageUrls[4],
            duration: 29,
            lessons: 5,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "behavioral-economics",
        title: "Behavioral Economics",
        description: "Psychology meets economics",
        courses: [
          {
            id: "be-1",
            title: "The Psychology of Money",
            description: "How emotions influence financial decisions",
            category: "Economics",
            imageUrl: imageUrls[0],
            duration: 34,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "be-2",
            title: "Nudges and Choice Architecture",
            description: "Designing better decision-making environments",
            category: "Economics",
            imageUrl: imageUrls[5],
            duration: 27,
            lessons: 5,
            progress: 0,
            chapters: [],
          },
          {
            id: "be-3",
            title: "Behavioral Finance",
            description: "Understanding irrational financial markets",
            category: "Economics",
            imageUrl: imageUrls[1],
            duration: 38,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
        ],
      },
    ],
  },
  {
    topicId: "philosophy",
    subtopics: [
      {
        id: "ancient-philosophy",
        title: "Ancient Philosophy",
        description: "The foundations of Western thought",
        courses: [
          {
            id: "phil-1",
            title: "Stoicism in Modern Life",
            description: "How ancient wisdom can help you navigate modern stress",
            category: "Philosophy",
            imageUrl: imageUrls[3],
            duration: 25,
            lessons: 5,
            progress: 0,
            chapters: [],
          },
          {
            id: "phil-2",
            title: "Plato's Republic",
            description: "Exploring justice, truth, and the ideal state",
            category: "Philosophy",
            imageUrl: imageUrls[4],
            duration: 48,
            lessons: 10,
            progress: 0,
            chapters: [],
          },
          {
            id: "phil-3",
            title: "Aristotle's Ethics",
            description: "Virtue, happiness, and the good life",
            category: "Philosophy",
            imageUrl: imageUrls[5],
            duration: 42,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "phil-4",
            title: "Socratic Method",
            description: "The art of questioning and critical thinking",
            category: "Philosophy",
            imageUrl: imageUrls[0],
            duration: 22,
            lessons: 4,
            progress: 0,
            chapters: [],
          },
          {
            id: "phil-5",
            title: "Epicureanism",
            description: "Pleasure, pain, and the pursuit of happiness",
            category: "Philosophy",
            imageUrl: imageUrls[1],
            duration: 26,
            lessons: 5,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "modern-philosophy",
        title: "Modern Philosophy",
        description: "Enlightenment thinkers and beyond",
        courses: [
          {
            id: "phil-6",
            title: "Kant's Critique of Pure Reason",
            description: "Understanding knowledge and perception",
            category: "Philosophy",
            imageUrl: imageUrls[2],
            duration: 55,
            lessons: 12,
            progress: 0,
            chapters: [],
          },
          {
            id: "phil-7",
            title: "Nietzsche and Existentialism",
            description: "Beyond good and evil, the will to power",
            category: "Philosophy",
            imageUrl: imageUrls[3],
            duration: 44,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "phil-8",
            title: "Utilitarianism",
            description: "The greatest good for the greatest number",
            category: "Philosophy",
            imageUrl: imageUrls[4],
            duration: 32,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "ethics",
        title: "Ethics",
        description: "Moral philosophy and right conduct",
        courses: [
          {
            id: "eth-1",
            title: "Applied Ethics",
            description: "Ethical dilemmas in modern society",
            category: "Philosophy",
            imageUrl: imageUrls[5],
            duration: 36,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "eth-2",
            title: "Bioethics",
            description: "Moral questions in medicine and biology",
            category: "Philosophy",
            imageUrl: imageUrls[0],
            duration: 40,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
          {
            id: "eth-3",
            title: "Environmental Ethics",
            description: "Our moral obligations to nature",
            category: "Philosophy",
            imageUrl: imageUrls[1],
            duration: 29,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
          {
            id: "eth-4",
            title: "Business Ethics",
            description: "Moral principles in commerce",
            category: "Philosophy",
            imageUrl: imageUrls[2],
            duration: 31,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
        ],
      },
    ],
  },
  {
    topicId: "science",
    subtopics: [
      {
        id: "biology",
        title: "Biology",
        description: "The study of life and living organisms",
        courses: [
          {
            id: "bio-1",
            title: "CRISPR & Gene Editing",
            description: "Understanding the future of human biology and ethics",
            category: "Science",
            imageUrl: imageUrls[4],
            duration: 35,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "bio-2",
            title: "Evolutionary Biology",
            description: "How species adapt and change over time",
            category: "Science",
            imageUrl: imageUrls[5],
            duration: 41,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
          {
            id: "bio-3",
            title: "Cell Biology",
            description: "The fundamental unit of life",
            category: "Science",
            imageUrl: imageUrls[0],
            duration: 38,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "bio-4",
            title: "Genetics and Heredity",
            description: "How traits are passed from generation to generation",
            category: "Science",
            imageUrl: imageUrls[1],
            duration: 33,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
          {
            id: "bio-5",
            title: "Ecology and Ecosystems",
            description: "Interactions between organisms and their environment",
            category: "Science",
            imageUrl: imageUrls[2],
            duration: 37,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "bio-6",
            title: "Neuroscience",
            description: "Understanding the brain and nervous system",
            category: "Science",
            imageUrl: imageUrls[3],
            duration: 45,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "physics",
        title: "Physics",
        description: "The fundamental laws of the universe",
        courses: [
          {
            id: "phys-1",
            title: "Quantum Mechanics",
            description: "The strange world of subatomic particles",
            category: "Science",
            imageUrl: imageUrls[4],
            duration: 52,
            lessons: 11,
            progress: 0,
            chapters: [],
          },
          {
            id: "phys-2",
            title: "Relativity Theory",
            description: "Einstein's revolutionary understanding of space and time",
            category: "Science",
            imageUrl: imageUrls[5],
            duration: 48,
            lessons: 10,
            progress: 0,
            chapters: [],
          },
          {
            id: "phys-3",
            title: "Thermodynamics",
            description: "Energy, entropy, and the laws of heat",
            category: "Science",
            imageUrl: imageUrls[0],
            duration: 36,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "phys-4",
            title: "Electromagnetism",
            description: "Electricity, magnetism, and their interactions",
            category: "Science",
            imageUrl: imageUrls[1],
            duration: 39,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "chemistry",
        title: "Chemistry",
        description: "The science of matter and its transformations",
        courses: [
          {
            id: "chem-1",
            title: "Organic Chemistry",
            description: "Carbon compounds and life's building blocks",
            category: "Science",
            imageUrl: imageUrls[2],
            duration: 44,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "chem-2",
            title: "Biochemistry",
            description: "Chemical processes in living organisms",
            category: "Science",
            imageUrl: imageUrls[3],
            duration: 40,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
          {
            id: "chem-3",
            title: "Physical Chemistry",
            description: "The physics of chemical systems",
            category: "Science",
            imageUrl: imageUrls[4],
            duration: 37,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "astronomy",
        title: "Astronomy",
        description: "Exploring the cosmos",
        courses: [
          {
            id: "astro-1",
            title: "The Solar System",
            description: "Our cosmic neighborhood",
            category: "Science",
            imageUrl: imageUrls[5],
            duration: 32,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
          {
            id: "astro-2",
            title: "Black Holes and Dark Matter",
            description: "The mysteries of the universe",
            category: "Science",
            imageUrl: imageUrls[0],
            duration: 46,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
        ],
      },
    ],
  },
  {
    topicId: "culture",
    subtopics: [
      {
        id: "world-cultures",
        title: "World Cultures",
        description: "Exploring diverse societies and traditions",
        courses: [
          {
            id: "cult-1",
            title: "Japanese Culture and Traditions",
            description: "From tea ceremonies to modern pop culture",
            category: "Culture",
            imageUrl: imageUrls[0],
            duration: 43,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
          {
            id: "cult-2",
            title: "African Cultural Heritage",
            description: "Rich traditions across the African continent",
            category: "Culture",
            imageUrl: imageUrls[1],
            duration: 39,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "cult-3",
            title: "Latin American Cultures",
            description: "The vibrant diversity of Central and South America",
            category: "Culture",
            imageUrl: imageUrls[2],
            duration: 41,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
          {
            id: "cult-4",
            title: "Middle Eastern Traditions",
            description: "Ancient customs and modern expressions",
            category: "Culture",
            imageUrl: imageUrls[3],
            duration: 37,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "cult-5",
            title: "Indigenous Cultures",
            description: "Preserving and understanding native traditions",
            category: "Culture",
            imageUrl: imageUrls[4],
            duration: 35,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "cultural-studies",
        title: "Cultural Studies",
        description: "Analyzing culture, identity, and society",
        courses: [
          {
            id: "cs-1",
            title: "Cultural Anthropology",
            description: "Understanding human societies and customs",
            category: "Culture",
            imageUrl: imageUrls[5],
            duration: 45,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "cs-2",
            title: "Food Culture",
            description: "How cuisine shapes identity and community",
            category: "Culture",
            imageUrl: imageUrls[0],
            duration: 28,
            lessons: 5,
            progress: 0,
            chapters: [],
          },
          {
            id: "cs-3",
            title: "Fashion and Identity",
            description: "Clothing as cultural expression",
            category: "Culture",
            imageUrl: imageUrls[1],
            duration: 31,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
        ],
      },
    ],
  },
  {
    topicId: "music",
    subtopics: [
      {
        id: "music-history",
        title: "Music History",
        description: "The evolution of musical expression",
        courses: [
          {
            id: "mh-1",
            title: "Classical Music Periods",
            description: "From Baroque to Romantic eras",
            category: "Music",
            imageUrl: imageUrls[2],
            duration: 50,
            lessons: 10,
            progress: 0,
            chapters: [],
          },
          {
            id: "mh-2",
            title: "Jazz History",
            description: "America's original art form",
            category: "Music",
            imageUrl: imageUrls[3],
            duration: 42,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
          {
            id: "mh-3",
            title: "Rock and Roll Evolution",
            description: "From blues roots to modern rock",
            category: "Music",
            imageUrl: imageUrls[4],
            duration: 38,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "mh-4",
            title: "Electronic Music",
            description: "Technology meets musical creativity",
            category: "Music",
            imageUrl: imageUrls[5],
            duration: 33,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
          {
            id: "mh-5",
            title: "World Music Traditions",
            description: "Musical expressions from around the globe",
            category: "Music",
            imageUrl: imageUrls[0],
            duration: 36,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "music-theory",
        title: "Music Theory",
        description: "Understanding the language of music",
        courses: [
          {
            id: "mt-1",
            title: "Fundamentals of Music Theory",
            description: "Notes, scales, and basic harmony",
            category: "Music",
            imageUrl: imageUrls[1],
            duration: 29,
            lessons: 5,
            progress: 0,
            chapters: [],
          },
          {
            id: "mt-2",
            title: "Composition Techniques",
            description: "Creating original musical works",
            category: "Music",
            imageUrl: imageUrls[2],
            duration: 44,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "mt-3",
            title: "Harmony and Counterpoint",
            description: "Advanced techniques in musical structure",
            category: "Music",
            imageUrl: imageUrls[3],
            duration: 47,
            lessons: 10,
            progress: 0,
            chapters: [],
          },
        ],
      },
    ],
  },
  {
    topicId: "politics",
    subtopics: [
      {
        id: "political-theory",
        title: "Political Theory",
        description: "Foundational ideas in political thought",
        courses: [
          {
            id: "pt-1",
            title: "Democracy and Its Challenges",
            description: "Understanding democratic systems and their evolution",
            category: "Politics",
            imageUrl: imageUrls[4],
            duration: 46,
            lessons: 9,
            progress: 0,
            chapters: [],
          },
          {
            id: "pt-2",
            title: "Political Ideologies",
            description: "Liberalism, conservatism, socialism, and beyond",
            category: "Politics",
            imageUrl: imageUrls[5],
            duration: 43,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
          {
            id: "pt-3",
            title: "Social Contract Theory",
            description: "The relationship between citizens and the state",
            category: "Politics",
            imageUrl: imageUrls[0],
            duration: 35,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "pt-4",
            title: "Political Economy",
            description: "The intersection of politics and economics",
            category: "Politics",
            imageUrl: imageUrls[1],
            duration: 40,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "international-relations",
        title: "International Relations",
        description: "Global politics and diplomacy",
        courses: [
          {
            id: "ir-1",
            title: "Diplomacy and Foreign Policy",
            description: "How nations interact on the world stage",
            category: "Politics",
            imageUrl: imageUrls[2],
            duration: 38,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "ir-2",
            title: "International Organizations",
            description: "The UN, EU, and global governance",
            category: "Politics",
            imageUrl: imageUrls[3],
            duration: 34,
            lessons: 6,
            progress: 0,
            chapters: [],
          },
          {
            id: "ir-3",
            title: "Conflict and Peace Studies",
            description: "Understanding war, peace, and conflict resolution",
            category: "Politics",
            imageUrl: imageUrls[4],
            duration: 41,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
        ],
      },
      {
        id: "comparative-politics",
        title: "Comparative Politics",
        description: "Comparing political systems across countries",
        courses: [
          {
            id: "cp-1",
            title: "European Political Systems",
            description: "Parliamentary and presidential models",
            category: "Politics",
            imageUrl: imageUrls[5],
            duration: 37,
            lessons: 7,
            progress: 0,
            chapters: [],
          },
          {
            id: "cp-2",
            title: "Asian Political Systems",
            description: "Diverse governance models across Asia",
            category: "Politics",
            imageUrl: imageUrls[0],
            duration: 39,
            lessons: 8,
            progress: 0,
            chapters: [],
          },
        ],
      },
    ],
  },
];

export const mockLibraryCourses: Course[] = [
  {
    id: "lib-1",
    title: "World War II: A Comprehensive Study",
    description: "Understanding one of history's darkest chapters",
    category: "History",
    imageUrl: imageUrls[1],
    duration: 45,
    lessons: 8,
    currentChapter: 4,
    totalChapters: 8,
    progress: 50,
    chapters: [
      { id: "lib-1-1", title: "The Rise of Fascism", duration: 6 },
      { id: "lib-1-2", title: "Invasion of Poland", duration: 5 },
      { id: "lib-1-3", title: "The Battle of Britain", duration: 6 },
      { id: "lib-1-4", title: "Operation Barbarossa", duration: 7 },
      { id: "lib-1-5", title: "Pearl Harbor and US Entry", duration: 5 },
      { id: "lib-1-6", title: "The Holocaust", duration: 6 },
      { id: "lib-1-7", title: "D-Day and Liberation", duration: 5 },
      { id: "lib-1-8", title: "The Atomic Bomb", duration: 5 },
    ],
  },
  {
    id: "lib-2",
    title: "Economic Policy",
    description: "Understanding economic policy and its impact",
    category: "Economics",
    imageUrl: imageUrls[2],
    duration: 30,
    lessons: 6,
    currentChapter: 2,
    totalChapters: 6,
    progress: 33,
    chapters: [
      { id: "lib-2-1", title: "Introduction to Economic Policy", duration: 5 },
      { id: "lib-2-2", title: "Fiscal Policy", duration: 5 },
      { id: "lib-2-3", title: "Monetary Policy", duration: 5 },
      { id: "lib-2-4", title: "Trade Policy", duration: 5 },
      { id: "lib-2-5", title: "Regulatory Policy", duration: 5 },
      { id: "lib-2-6", title: "Policy Implementation", duration: 5 },
    ],
  },
  {
    id: "lib-3",
    title: "Financial Markets",
    description: "Introduction to financial markets and trading",
    category: "Economics",
    imageUrl: imageUrls[2],
    duration: 35,
    lessons: 7,
    currentChapter: 1,
    totalChapters: 7,
    progress: 14,
    chapters: [
      { id: "lib-3-1", title: "Introduction to Financial Markets", duration: 5 },
      { id: "lib-3-2", title: "Stock Markets", duration: 5 },
      { id: "lib-3-3", title: "Bond Markets", duration: 5 },
      { id: "lib-3-4", title: "Derivatives and Futures", duration: 5 },
      { id: "lib-3-5", title: "Foreign Exchange Markets", duration: 5 },
      { id: "lib-3-6", title: "Market Analysis", duration: 5 },
      { id: "lib-3-7", title: "Trading Strategies", duration: 5 },
    ],
  },
  {
    id: "lib-4",
    title: "Ancient Philosophy",
    description: "Exploring the foundations of Western thought",
    category: "Philosophy",
    imageUrl: imageUrls[3],
    duration: 40,
    lessons: 10,
    currentChapter: 10,
    totalChapters: 10,
    progress: 100,
    chapters: [
      { id: "lib-4-1", title: "Pre-Socratic Philosophers", duration: 4 },
      { id: "lib-4-2", title: "Socrates and the Socratic Method", duration: 4 },
      { id: "lib-4-3", title: "Plato's Theory of Forms", duration: 4 },
      { id: "lib-4-4", title: "Aristotle's Ethics", duration: 4 },
      { id: "lib-4-5", title: "Stoicism", duration: 4 },
      { id: "lib-4-6", title: "Epicureanism", duration: 4 },
      { id: "lib-4-7", title: "Skepticism", duration: 4 },
      { id: "lib-4-8", title: "Neoplatonism", duration: 4 },
      { id: "lib-4-9", title: "Roman Philosophy", duration: 4 },
      { id: "lib-4-10", title: "Legacy of Ancient Philosophy", duration: 4 },
    ],
  },
  {
    id: "lib-5",
    title: "Modern Art Movements",
    description: "Understanding contemporary art",
    category: "Art",
    imageUrl: imageUrls[0],
    duration: 25,
    lessons: 5,
    currentChapter: 5,
    totalChapters: 5,
    progress: 100,
    chapters: [
      { id: "lib-5-1", title: "Impressionism", duration: 5 },
      { id: "lib-5-2", title: "Cubism", duration: 5 },
      { id: "lib-5-3", title: "Surrealism", duration: 5 },
      { id: "lib-5-4", title: "Abstract Expressionism", duration: 5 },
      { id: "lib-5-5", title: "Pop Art", duration: 5 },
    ],
  },
];

